name = "WoodburyFactorizations"
uuid = "9f1bac23-581c-4ebc-bd36-df60d764636d"
authors = ["Sebastian Ament <sebastianeament@gmail.com>"]
version = "1.0.2"

[deps]
LazyInverses = "9f18896c-49a9-43cc-8eef-c455a8a119c6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"
LazyInverses = "1.1"
